[package]
name = "project-euler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6.3"
itertools = "0.12.1"
num-bigint = "0.4.4"
num-integer = "0.1.45"
num-traits = "0.2.17"
